### ISSUE TITLE
Wrong Windows Defender mapping

### ISSUE THREAD

**Issue by n00bsteam** [theflakes/sigma_to_wazuh#10]
Hello!

Looks like you have wrong rule mapping:

```[if_sid_product]
windows = 18100, 60000, 60001, 60002, 60003, 60004, 60005, 60006, 60007, 60008, 60009, 60010, 60011, 60012
windows_defender = 18100, 60000, 60001, 60002, 60003, 60004, 60005, 60006, 60007, 60008, 60009, 60010, 60011, 60012
```
Wazuh Windows Defender Rules are:
```
<!-- MS Windows Defender rules -->
<group name="windows,windows_defender,">
  <rule id="62100" level="0">
    <if_sid>60005</if_sid>
    <field name="win.system.severityValue">^INFORMATION$</field>
    <description>Windows Defender informational event</description>
    <options>no_full_log</options>
  </rule>

  <rule id="62101" level="0">
    <if_sid>60005</if_sid>
    <field name="win.system.severityValue">^WARNING$</field>
    <description>Windows Defender warning event</description>
    <options>no_full_log</options>
    <group>pci_dss_10.6.1,gpg13_4.12,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

  <rule id="62102" level="5">
    <if_sid>60005</if_sid>
    <field name="win.system.severityValue">^ERROR$</field>
    <description>Windows Defender error event</description>
    <options>no_full_log</options>
    <group>system_error,pci_dss_10.6.1,gpg13_4.3,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
  ```

So I assume it should be like this:
```[if_sid_product]
windows = 18100, 60000, 60001, 60002, 60003, 60004, 60005, 60006, 60007, 60008, 60009, 60010, 60011, 60012
windows_defender = 62100, 62101, 62102
```

**Comment by theflakes** [comment]
Thanks, I hadn't mapped the if_sids out for Windows Defender yet. Wasn't sure if they could trigger any generic Windows rules or not. My concern is making sure we aren't missing any hits no matter the parent rule that triggers. I'll add those three as if_sids and do a little research.

**Comment by theflakes** [comment]
I'll add these three as if_sids. But, in each of those rules they have an if_sid of 60005 which is included already. Any rule with a higher level that matches will take precedence so the if_sid as it is now should work.

**Comment by n00bsteam** [comment]
Only it was necessary to leave these 3, the rest must be removed.
Before writing issue, I checked and there were a lot of false alerts.

**Comment by n00bsteam** [comment]
And it seems to me that if the child rule has a choice of 2 levels higher, then both top-level rules will not work simultaneously, but only one will work. But it's better to check with Wazuh.

**Comment by theflakes** [comment]
Try it now, they are removed.

**Comment by theflakes** [comment]
It should follow the chain, child rule only takes affect if its logic is a match. Otherwise last match in the chain applies. If I'm understanding your statement correctly.

**Comment by theflakes** [comment]
Further research that only 60005 needs to be in the if_sid. But, now need to find the product ID used in Sigma rules.

**Comment by n00bsteam** [comment]
![image](https://user-images.githubusercontent.com/47595602/162628185-4c7e2b76-4230-4e3e-b52e-0f1732760e8b.png)

**Comment by theflakes** [comment]
This will be fixed in the next push. Finding at least two different service names for Windows Defender: windefend and Microsoft Windows Defender.

**Comment by theflakes** [comment]
Should be fixed now. Removed 60005 from the if_sid of Windows rules.

**Comment by theflakes** [comment]
Working now I think, will reopen if not.
