### ISSUE TITLE
Error validating XML

### ISSUE THREAD

**Issue by n0rthl1ght** [theflakes/sigma_to_wazuh#12]
Hey!
There is awesome that someone working on converter of rules to wazuh!
I'll be active tester :D

Have a problem with validating converted XML with default settings in config.ini.
I think problem in groups like antivirus, rpc_firewall, application and so on that not in Wazuh group rules lists

**Comment by theflakes** [comment]
Thanks, can you provide the exact error and Sigma rule(s) that are generating the error and any other information around the error? thanks

**Comment by n0rthl1ght** [comment]
I just tried to paste whole text from converted xml. Hmm, there is the problem with lost </group> somewhere. I pasted the first rule, and it's ok

**Comment by n0rthl1ght** [comment]
I think the problem with \ for a new line. I mean text wrap

**Comment by n0rthl1ght** [comment]
Found the example!![image](https://user-images.githubusercontent.com/92512883/162982276-92ac339b-6c70-4805-8310-27392e667f13.jpeg)

**Comment by theflakes** [comment]
Thanks for finding this, should be fixed now. Problem was regex was not being escaped properly on some rules.

**Comment by theflakes** [comment]
The rule its failed on is also not having its logic converted correctly.

**Comment by n0rthl1ght** [comment]
I will test the new version, when it's ready. I hope it'll be ok 👍

**Comment by n0rthl1ght** [comment]
Tested again and have the same problem.
![image](https://user-images.githubusercontent.com/92512883/163121235-8f2522d0-95fc-4d0b-ae57-035594076455.png)

**Comment by n0rthl1ght** [comment]
Got the answer

![image](https://user-images.githubusercontent.com/92512883/163168401-649e11d7-8305-4621-bcd9-bdc9ead503f4.png)

**Comment by theflakes** [comment]
Think this is fixed but there have been a lot of changes since this was reported.

Still working on converting more complex Sigma logic to Wazuh. Not sure if I'll ever get it working fully tbh.
